package indi.ssuf1998.vqrscan.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import indi.ssuf1998.vqrscan.HistoryItem;

import indi.ssuf1998.vqrscan.greendao.HistoryItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyItemDaoConfig;

    private final HistoryItemDao historyItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyItemDaoConfig = daoConfigMap.get(HistoryItemDao.class).clone();
        historyItemDaoConfig.initIdentityScope(type);

        historyItemDao = new HistoryItemDao(historyItemDaoConfig, this);

        registerDao(HistoryItem.class, historyItemDao);
    }
    
    public void clear() {
        historyItemDaoConfig.clearIdentityScope();
    }

    public HistoryItemDao getHistoryItemDao() {
        return historyItemDao;
    }

}
