package indi.ssuf1998.vqrscan.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import indi.ssuf1998.vqrscan.HistoryItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_ITEM".
*/
public class HistoryItemDao extends AbstractDao<HistoryItem, Long> {

    public static final String TABLENAME = "HISTORY_ITEM";

    /**
     * Properties of entity HistoryItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ResultText = new Property(1, String.class, "resultText", false, "RESULT_TEXT");
        public final static Property ResultType = new Property(2, int.class, "resultType", false, "RESULT_TYPE");
        public final static Property CreateTime = new Property(3, long.class, "createTime", false, "CREATE_TIME");
    }


    public HistoryItemDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RESULT_TEXT\" TEXT," + // 1: resultText
                "\"RESULT_TYPE\" INTEGER NOT NULL ," + // 2: resultType
                "\"CREATE_TIME\" INTEGER NOT NULL );"); // 3: createTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistoryItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String resultText = entity.getResultText();
        if (resultText != null) {
            stmt.bindString(2, resultText);
        }
        stmt.bindLong(3, entity.getResultType());
        stmt.bindLong(4, entity.getCreateTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistoryItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String resultText = entity.getResultText();
        if (resultText != null) {
            stmt.bindString(2, resultText);
        }
        stmt.bindLong(3, entity.getResultType());
        stmt.bindLong(4, entity.getCreateTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HistoryItem readEntity(Cursor cursor, int offset) {
        HistoryItem entity = new HistoryItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // resultText
            cursor.getInt(offset + 2), // resultType
            cursor.getLong(offset + 3) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistoryItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setResultText(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setResultType(cursor.getInt(offset + 2));
        entity.setCreateTime(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HistoryItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HistoryItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HistoryItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
